[package]
name = "ghost2zola"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
bzip2 = "0.4.1"
libflate = "1.0.2"
rusqlite = "0.24.1"
structopt = "0.3.20"
tar = "0.4.30"
tree_magic = "0.2.3"
thiserror = "1.0.21"
anyhow = "1.0.33"
