[package]
name = "ghost2zola"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
chrono = { version = "0.4.19", features = [ "serde" ] }
mobiledoc = { path = "../mobiledoc" }
serde = { version = "1.0.117", features = [ "derive" ] }
serde_json = "1.0.59"
structopt = "0.3.20"
toml = "0.5.7"
